user_index:
    path:     /user
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/showuser
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

user_new:
    path:     /newuser
    defaults: { _controller: "UserBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edituser
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/deleteuser
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE
