sponsor_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:sponsor:index" }
    methods:  GET

sponsor_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:sponsor:show" }
    methods:  GET

sponsor_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:sponsor:new" }
    methods:  [GET, POST]

sponsor_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:sponsor:edit" }
    methods:  [GET, POST]

sponsor_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:sponsor:delete" }
    methods:  DELETE
