<?php

namespace BackOfficeBundle\Repository;

/**
 * sponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sponsorRepository extends \Doctrine\ORM\EntityRepository
{
}
